--- drivers/net/wireless/realtek/Makefile
+++ drivers/net/wireless/realtek/Makefile
@@ -7,4 +7,4 @@ obj-$(CONFIG_RTL8187)		+= rtl818x/
 obj-$(CONFIG_RTLWIFI)		+= rtlwifi/
 obj-$(CONFIG_RTL8XXXU)		+= rtl8xxxu/
 obj-$(CONFIG_88XXAU)		+= rtl8812au/
-
+obj-$(CONFIG_RTW88)		+= rtw88/
